---
kind: pipeline
type: kubernetes
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t ref-data-gov-api-spec:$${DRONE_COMMIT_SHA} .
  when:
    branch:
    - master
    event:
    - push

- name: vulnerability-scan
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  environment:
    DOCKERFILE: Dockerfile
    IMAGE_NAME: ref-data-gov-api-spec:${DRONE_COMMIT_SHA}
    LOCAL_IMAGE: true
    TOLERATE: low
    WHITELIST_FILE: whitelist
  when:
    branch:
    - master
    event:
    - push

- name: image_to_quay
  image: plugins/docker
  settings:
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-gov-api-spec
    tags:
    - ${DRONE_BUILD_NUMBER}
    - ${DRONE_COMMIT_SHA}
    - latest
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
    DOCKER_USERNAME:
      from_secret: DOCKER_USERNAME
  when:
    branch:
    - master
    event:
    - push
    - promote

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd
  commands:
  - export HOSTNAME=$${DEV_HOSTNAME}
  - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
  - export KUBE_SERVER=$${DEV_KUBE_SERVER}
  - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
  - kd --insecure-skip-tls-verify -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
  environment:
    DEV_HOSTNAME:
      from_secret: DEV_HOSTNAME
    DEV_KUBE_NAMESPACE:
      from_secret: DEV_KUBE_NAMESPACE
    DEV_KUBE_SERVER:
      from_secret: DEV_KUBE_SERVER
    DEV_KUBE_TOKEN:
      from_secret: DEV_KUBE_TOKEN
  when:
    branch:
    - master
    event:
    - push
    - promote

- name: notify
  pull: if-not-exists
  image: plugins/slack
  settings:
    channel: cop-deployments
    template: "{{#build.deployTo}}\n  *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*\n  {{build.link}}\n{{else}}\n  *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*\n  {{build.link}}\n{{/build.deployTo}}\n"
    username: Drone Build Watcher
  environment:
    SLACK_WEBHOOK:
      from_secret: SLACK_WEBHOOK
  when:
    branch:
    - master
    event:
    - push
    - promote
    status:
    - success
    - failure

services:
- name: docker
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

- name: anchore-submission-server
  pull: always
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/anchore-submission:latest
  commands:
  - /run.sh server

...
