openapi: 3.0.0

info:
  title: Reference Data Service API
  description: "Some more description goes here"
  version: "0.0.1"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

servers:
- url: https://{environment}.homeoffice.gov.uk/v1
  variables:
    environment:
      default: api    # Production server
      enum:
        - api.refdata         # Production server
        - api.refdata-dev     # Development server
        - api.refdata-staging # Staging server

tags:
- name: "datasets"
  description: "Data sets are the collection of reference data tables"
  externalDocs:
    description: "Visit the project Wiki"
    url: "https://github.com/UKHomeOffice/RefDataBAU/wiki"
- name: "items"
  description: "Items are the individual records within the reference data tables"

paths:
  /datasets:
    get:
      tags:
        - datasets
      summary: Gets the list of datasets
      description: Longer description goes here
      operationId: getDatasets
      responses:
        200:
          description: A list of datasets
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: countries
        401:
          description: The request requires user authentication, which has been failed

  /datasets/{name}:
    get:
      tags:
        - datasets
      summary: Gets data items within a data set (supports pagination)
      description: Longer description goes here
      operationId: getDataset
      responses:
        200:
          description: Success
    patch:
      tags:
        - datasets
      summary: Request an update to the definition of a dataset
      description: Longer description goes here
      operationId: patchDataset
      responses:
        202:
          description: Accepted
    delete:
      tags:
        - datasets
      summary: Request the deletion of a dataset
      description: Longer description goes here
      operationId: deleteDataset
      responses:
        202:
          description: Accepted

  /datasets/{name}/schema:
    get:
      tags:
        - datasets
      summary: Gets the schema of the dataset
      description: Longer description goes here
      operationId: getDatasetSchema
      responses:
        200:
          description: Success

  /datasets/{name}/search:
    get:
      tags:
        - datasets
      summary: Search a dataset
      description: Longer description goes here
      operationId: searchDataset
      responses:
        200:
          description: Results of a search on a dataset
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: object
                    example: [
                        {
                          id: 8,
                          countryCode: GBR
                        }
                      ]
